/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication2_lv_lv2_Lv2Activity */

#ifndef _Included_com_example_myapplication2_lv_lv2_Lv2Activity
#define _Included_com_example_myapplication2_lv_lv2_Lv2Activity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication2_lv_lv2_Lv2Activity
 * Method:    getNativeUsername
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication2_lv_lv2_Lv2Activity_getNativeUsername
(JNIEnv *, jobject);

/*
 * Class:     com_example_myapplication2_lv_lv2_Lv2Activity
 * Method:    getNativePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication2_lv_lv2_Lv2Activity_getNativePassword
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
