/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication2_lv_lv3_Lv3Activity */

#ifndef _Included_com_example_myapplication2_lv_lv3_Lv3Activity
#define _Included_com_example_myapplication2_lv_lv3_Lv3Activity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication2_lv_lv3_Lv3Activity
 * Method:    getLv3String
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication2_lv_lv3_Lv3Activity_getLv3String__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_myapplication2_lv_lv3_Lv3Activity
 * Method:    getLv3String
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication2_lv_lv3_Lv3Activity_getLv3String__Z
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
