/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fridatestexample_lv_lv5_Lv5Activity */

#ifndef _Included_com_example_fridatestexample_lv_lv5_Lv5Activity
#define _Included_com_example_fridatestexample_lv_lv5_Lv5Activity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fridatestexample_lv_lv5_Lv5Activity
 * Method:    compareString
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_fridatestexample_lv_lv5_Lv5Activity_isSameString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
