/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fridatestexample_lv_lv6_Lv6Activity */

#ifndef _Included_com_example_fridatestexample_lv_lv6_Lv6Activity
#define _Included_com_example_fridatestexample_lv_lv6_Lv6Activity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fridatestexample_lv_lv6_Lv6Activity
 * Method:    isDebuging
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_fridatestexample_lv_lv6_Lv6Activity_isDebuging(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
