/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fridatestexample_MainActivity */

#ifndef _Included_com_example_fridatestexample_MainActivity
#define _Included_com_example_fridatestexample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fridatestexample_MainActivity
 * Method:    getHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fridatestexample_MainActivity_getHelloWorld(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
